Analysis_Info= {
    'GMNIA':{
                'Residual_Stress':True,
                'Elastic_analysis':False,
                'Second_order_effects':True,
                'stiffness_reduction':0.9,
                'strength_reduction':0.9,
                'Geometric_Imperfection':True,
                'Notional_load':False
                },
    'GMNA':{
                'Residual_Stress':True,
                'Elastic_analysis':False,
                'Second_order_effects':True,
                'stiffness_reduction':0.9,
                'strength_reduction':0.9,
                'Geometric_Imperfection':False,
                'Notional_load':False
                },
    'GNIA':{
                'Residual_Stress':False,
                'Elastic_analysis':True,
                'Second_order_effects':True,
                'stiffness_reduction':0.8,
                'strength_reduction':1,
                'Geometric_Imperfection':True,
                'Notional_load':False
                },
    'GNA_Notional_Loads':{
                'Residual_Stress':False,
                'Elastic_analysis':True,
                'Second_order_effects':True,
                'stiffness_reduction':0.8,
                'strength_reduction':1,
                'Geometric_Imperfection':False,
                'Notional_load':True
                },
    '1st_order_elastic':{
                'Residual_Stress':False,
                'Elastic_analysis':True,
                'Second_order_effects':False,
                'stiffness_reduction':0.8,
                'strength_reduction':1,
                'Geometric_Imperfection':False,
                'Notional_load':False
                },
    'GNA':{
                'Residual_Stress':False,
                'Elastic_analysis':True,
                'Second_order_effects':True,
                'stiffness_reduction':0.8,
                'strength_reduction':1,
                'Geometric_Imperfection':False,
                'Notional_load':False
                }
            }