import numpy as np
###### Frame_Info={} should be always exist in this file. 

Frame_Info={'W14X43_x_1_7.391_50_ksi_support_f_FtR1': {'Frame_id': 'W14X43_x_1_7.391_50_ksi_support_f_FtR1',
                                            'story_height': [7.391],
                                            'column_section': {'common_and_exceptions': {'common': ('W14X43', 'x')}},
                                            'Material_type': '50_ksi',
                                            'Leaning_column': False,
                                            'bay_width': [],
                                            'column_no_of_ele': 4,
                                            'beam_no_of_ele': 4,
                                            'beam_section': {'common_and_exceptions': {'common': 'W27X84'}},
                                            'support': 'f',
                                            'load_comb_multipliers': [1, 0, 0, 1],
                                            'floor_to_roof_load_ratio': 1,
                                            'D_floor_intensity': 1000.0,
                                            'L_floor_intensity': 0.0,
                                            'L_roof_intensity': 0.0,
                                            'wind_load_same_for_all_h': False,
                                            'Base_Wind_load': 10.0,
                                            'Wall_load': 0,
                                            'geometric_imperfection_ratio': 0.002,
                                            'initial_out_of_straightness_ratio': 0.001,
                                            'Leaning_column_offset': 2,
                                            'Leaning_Column_load_ratio': 0,
                                            'floor_nodes_free': False,
                                            'D_roof_intensity': 1000.0,
                                            'Leaning_column_floor_load': 0,
                                            'Leaning_column_roof_load': 0},
 'W14X43_y_1_2.208_50_ksi_support_f_FtR1': {'Frame_id': 'W14X43_y_1_2.208_50_ksi_support_f_FtR1',
                                            'story_height': [2.208],
                                            'column_section': {'common_and_exceptions': {'common': ('W14X43', 'y')}},
                                            'Material_type': '50_ksi',
                                            'Leaning_column': False,
                                            'bay_width': [],
                                            'column_no_of_ele': 4,
                                            'beam_no_of_ele': 4,
                                            'beam_section': {'common_and_exceptions': {'common': 'W27X84'}},
                                            'support': 'f',
                                            'load_comb_multipliers': [1, 0, 0, 1],
                                            'floor_to_roof_load_ratio': 1,
                                            'D_floor_intensity': 1000.0,
                                            'L_floor_intensity': 0.0,
                                            'L_roof_intensity': 0.0,
                                            'wind_load_same_for_all_h': False,
                                            'Base_Wind_load': 10.0,
                                            'Wall_load': 0,
                                            'geometric_imperfection_ratio': 0.002,
                                            'initial_out_of_straightness_ratio': 0.001,
                                            'Leaning_column_offset': 2,
                                            'Leaning_Column_load_ratio': 0,
                                            'floor_nodes_free': False,
                                            'D_roof_intensity': 1000.0,
                                            'Leaning_column_floor_load': 0,
                                            'Leaning_column_roof_load': 0},
 'W14X43_x_1_6.209_50_ksi_support_p_FtR1': {'Frame_id': 'W14X43_x_1_6.209_50_ksi_support_p_FtR1',
                                            'story_height': [6.209],
                                            'column_section': {'common_and_exceptions': {'common': ('W14X43', 'x')}},
                                            'Material_type': '50_ksi',
                                            'Leaning_column': False,
                                            'bay_width': [],
                                            'column_no_of_ele': 4,
                                            'beam_no_of_ele': 4,
                                            'beam_section': {'common_and_exceptions': {'common': 'W27X84'}},
                                            'support': 'p',
                                            'load_comb_multipliers': [1, 0, 0, 1],
                                            'floor_to_roof_load_ratio': 1,
                                            'D_floor_intensity': 1000.0,
                                            'L_floor_intensity': 0.0,
                                            'L_roof_intensity': 0.0,
                                            'wind_load_same_for_all_h': False,
                                            'Base_Wind_load': 10.0,
                                            'Wall_load': 0,
                                            'geometric_imperfection_ratio': 0.002,
                                            'initial_out_of_straightness_ratio': 0.001,
                                            'Leaning_column_offset': 2,
                                            'Leaning_Column_load_ratio': 0,
                                            'floor_nodes_free': False,
                                            'D_roof_intensity': 1000.0,
                                            'Leaning_column_floor_load': 0,
                                            'Leaning_column_roof_load': 0},
 'W14X43_x_1_7.983_50_ksi_support_p_FtR1': {'Frame_id': 'W14X43_x_1_7.983_50_ksi_support_p_FtR1',
                                            'story_height': [7.983],
                                            'column_section': {'common_and_exceptions': {'common': ('W14X43', 'x')}},
                                            'Material_type': '50_ksi',
                                            'Leaning_column': False,
                                            'bay_width': [],
                                            'column_no_of_ele': 4,
                                            'beam_no_of_ele': 4,
                                            'beam_section': {'common_and_exceptions': {'common': 'W27X84'}},
                                            'support': 'p',
                                            'load_comb_multipliers': [1, 0, 0, 1],
                                            'floor_to_roof_load_ratio': 1,
                                            'D_floor_intensity': 1000.0,
                                            'L_floor_intensity': 0.0,
                                            'L_roof_intensity': 0.0,
                                            'wind_load_same_for_all_h': False,
                                            'Base_Wind_load': 10.0,
                                            'Wall_load': 0,
                                            'geometric_imperfection_ratio': 0.002,
                                            'initial_out_of_straightness_ratio': 0.001,
                                            'Leaning_column_offset': 2,
                                            'Leaning_Column_load_ratio': 0,
                                            'floor_nodes_free': False,
                                            'D_roof_intensity': 1000.0,
                                            'Leaning_column_floor_load': 0,
                                            'Leaning_column_roof_load': 0},
 'W14X43_y_1_2.4_50_ksi_support_p_FtR1': {'Frame_id': 'W14X43_y_1_2.4_50_ksi_support_p_FtR1',
                                          'story_height': [2.4],
                                          'column_section': {'common_and_exceptions': {'common': ('W14X43', 'y')}},
                                          'Material_type': '50_ksi',
                                          'Leaning_column': False,
                                          'bay_width': [],
                                          'column_no_of_ele': 4,
                                          'beam_no_of_ele': 4,
                                          'beam_section': {'common_and_exceptions': {'common': 'W27X84'}},
                                          'support': 'p',
                                          'load_comb_multipliers': [1, 0, 0, 1],
                                          'floor_to_roof_load_ratio': 1,
                                          'D_floor_intensity': 1000.0,
                                          'L_floor_intensity': 0.0,
                                          'L_roof_intensity': 0.0,
                                          'wind_load_same_for_all_h': False,
                                          'Base_Wind_load': 10.0,
                                          'Wall_load': 0,
                                          'geometric_imperfection_ratio': 0.002,
                                          'initial_out_of_straightness_ratio': 0.001,
                                          'Leaning_column_offset': 2,
                                          'Leaning_Column_load_ratio': 0,
                                          'floor_nodes_free': False,
                                          'D_roof_intensity': 1000.0,
                                          'Leaning_column_floor_load': 0,
                                          'Leaning_column_roof_load': 0}}